### ISSUE TITLE
[OC] [Patch] Rename GPRW to XPRW for SSDT-GPRW.aml

### ISSUE THREAD

**Issue by lucrative-menace** [erinviegas/Lenovo-Ideapad-330S-14IKB#2]
The purpose of SSDT-GPRW.aml is to act as a tether between the real GPRW method in ACPI and the _PRW methods in different devices (e.g. GLAN) in ACPI, so that some devices (e.g. GLAN) do not wake the device from sleep. When using this SSDT, shouldn't there be a patch to rename the original GPRW method to XPRW, so that the one defined in the SSDT itself can be of use? Without this patch, laptop was not able to enter sleep state as "GLAN" kept it awake.

More info: https://dortania.github.io/OpenCore-Post-Install/usb/misc/instant-wake.html
Patch: https://github.com/dortania/OpenCore-Post-Install/blob/master/extra-files/GPRW-Patch.plist

With the patch in ACPI->Patch, sleep works fine (the lid issue persists, cannot find a solution to that currently).

**Comment by erinviegas** [comment]
Sleep works regardless of whether this patch is included or not on clover. Forgot to add it to the opencore config. Will be added.
