### ISSUE TITLE
ALC256 

### ISSUE THREAD

**Issue by abdllhcrk** [erinviegas/Lenovo-Ideapad-330S-14IKB#5]
Hello, can you help me to add New codec support for ALC256 ? I tried everything but i really don't know what to do. If you want, I can send my Codec Dump file.

**Comment by erinviegas** [comment]
Attach the file there. I'll take a look. Have you tried any existing layouts? Which works best? Also which device are you using?

**Comment by abdllhcrk** [comment]
Thank you so much for your help. I am using Acer Swift 3 laptop. Yes, I tried all layouts for ALC256. With 21 and 66 layouts, speakers are working well and Internal Mic is recognized by system but mic not working. Appearently, 21 and 66 layouts are the best for me now. Actually I need your help for my Built in Internal Mic.

[codec dump.zip](https://github.com/erinviegas/Lenovo-Ideapad-330S-14IKB/files/5516112/codec.dump.zip)

**Comment by erinviegas** [comment]
> Thank you so much for your help. I am using Acer Swift 3 laptop. Yes, I tried all layouts for ALC256. With 21 and 66 layouts, speakers are working well and Internal Mic is recognized by system but mic not working. Appearently, 21 and 66 layouts are the best for me now. Actually I need your help for my Built in Internal Mic.
> 
> [codec dump.zip](https://github.com/erinviegas/Lenovo-Ideapad-330S-14IKB/files/5516112/codec.dump.zip)

Send me a screenshot of your current config like this.
![Screenshot 2020-11-10 at 4 07 22 PM](https://user-images.githubusercontent.com/52821527/98663336-f2188500-236e-11eb-90c7-a83493d4c800.png)

**Comment by abdllhcrk** [comment]
Here it is

![Screen Shot 2020-11-10 at 14 27 26](https://user-images.githubusercontent.com/73475970/98668455-f76ed300-2360-11eb-97bb-d5fa9c88fccf.png)

**Comment by erinviegas** [comment]
Looks like your issue is a little more complicated. From your codec dump I can see that the mic doesn't exist, which leads me to think that it's a part of your camera array. Sadly I won't be able to help with this as I do not have the time to spend to get deep into finding a fix. But I did find a thread which may be a starting point for you here: https://www.tonymacx86.com/threads/guide-acer-swift-3-i5-8250u-mojave.249160/page-11
Good luck!

**Comment by abdllhcrk** [comment]
Ok thank you so much for your help.
