### ISSUE TITLE
BrightnessKey Remap

### ISSUE THREAD

**Issue by NinjaWolf** [erinviegas/Lenovo-Ideapad-330S-14IKB#7]
Isn't so much an issue, so feel free to close. However noted in O.C. changelogs, so I thought I would mention as I base my EFI Closely off yours.

https://github.com/acidanthera/BrightnessKeys

Per OC Changelog, we should be using this instead of a ssdt. No patches needed.

**Comment by erinviegas** [comment]
Cool, just tested it out. Will update repo to reflect this.
